### ISSUE TITLE
Demo segfaults on start up after FlutterEngineRun

### ISSUE THREAD

**Issue by j4qfrost** [gliheng/flutter-app-demo#5]
Distro: Arch Linux
Kernel ver: 5.3.8
Flutter ver: 1.10.16-pre.93
Rust ver: 1.38.0

This also occurs for me in the template.

Initially I had though that the problem was isolated to window creation, but I threw in thread sleeps to narrow down where the cause of the problem was and it looks like a deadlock is happening after [flutter_engine_sys::FlutterEngineRun](https://github.com/flutter-rs/flutter-rs/blob/0a083fa3ff7fe2ca1288ae119553b02ac01d8226/flutter-engine/src/lib.rs#L319)  is run within the engine. The segfault happens directly after that function when calling thread::sleep.

dmesg output:
```io.flutter.ui[63336]: segfault at 0 ip 00007f4e900d966c sp 00007f4e8b2dc0d0 error 4 in libflutter_engine.so[7f4e8fc9d000+a20000]```
This might indicate a null pointer?

It might be more appropriate to put this in the flutter-rs repo.

**Comment by j4qfrost** [comment]
I made a Dockerfile real quick to isolate the issue some more. I think the issue might be that my kernel is not compatible with the flutter library. I'll try to get my hands on a better test machine.

To use this Dockerfile you will need to change the paths for flutter-plugin and flutter-engine in Cargo.toml
https://gist.github.com/j4qfrost/67ba0ac97753e9a48b5f8ce946340498
```docker run --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --device=/dev/dri:/dev/dri  flutter-app-demo```

Update: downgraded the kernel to 4.18.12 with the same results.

**Comment by j4qfrost** [comment]
As a heads up, I was able to start up @999eagle 's okuna-desktop project with some asset bundling errors, So I don't really know where to look to move forward on this one. Could it possibly be a glfw compatibility issue?

**Comment by dvc94ch** [comment]
@j4qfrost the issue is probably an incompatible `icudtl.dat` file. I'll update the demo tomorrow. We now bundle `icudtl.dat` with our engine builds, so this issue shouldn't occur if you use `cargo-flutter`.

**Comment by j4qfrost** [comment]
Cool. Also have you guys kept track with this branch? https://github.com/cloudwebrtc/flutter-engine/tree/texture_glfw

Not sure if it would be a good idea to start switching over or plan to. The branch looks stable with some change requests, but I'm just a noob.

**Comment by dvc94ch** [comment]
Yeah, we still need macosx and windows support so that it's not a regression. If you have experience with macosx or windows and want to help out, that would be awesome.
